"""
app/services/evidence_disclaimer.py
====================================================================
The evidence-support disclaimer -- §7 of
docs/methodology/input_admission_projection_gate_architecture_v1.1_FROZEN.md
(requirements S1 to S4, and §7.2's support matrix).

Why this module is NEW, when S3 says to use an existing template
----------------------------------------------------------------
S3 reads "Use the existing server-rendered parameterised template. Do not
add static text." No such template exists in this codebase, and this is
worth stating plainly rather than quietly working around: `disclaimer` is
one of the seven fields the LLM itself writes (REPORT_CONTENT_FIELDS in
prompt_builder.py), so up to now the disclaimer has been model-authored
free text, not server-rendered anything. A real generated example from
the Phase 7 dev log -- "Clinical uncertainty due to low agreement score
(0.60)" -- shows the shape of the problem exactly: it is prose the model
chose, and it reads ONE signal.

That single-signal reading is the specific failure §7.1's Warning
describes. Five retrieved cases can all sit below the retrieval floor and
still all carry the same label; agreement is then high, retrieval support
is low, and a disclaimer written from the agreement score alone announces
high confidence in what is actually weak evidence -- "the opposite of the
truth", in the document's words.

So S3's requirement is implemented, and only its "existing" is wrong
about this repository. The substance -- server-rendered, parameterised,
never static text, reading BOTH signals (§7.1's Rule) -- is what this
module provides, and building the template it names is not a change to
the architecture it is named in. The discrepancy is reported rather than
silently absorbed.

What replaces what
------------------
ReportGenerationService overwrites `content.disclaimer` with the output of
render_disclaimer() after generation. The LLM still emits a disclaimer
field (the 7-field output contract and its marker format are untouched,
and Phase 20 traced 17 real generation failures to that contract, so it is
not something to disturb for this); its text is simply not what reaches
the report. `disclaimer` was already AI-set-once and outside the five
doctor-editable fields (EditableReportField), so nothing a doctor can edit
changes hands here -- it moves from model-authored to server-authored,
which is the direction S3, S8 and S9 all point.

The parameters (S2)
-------------------
Exactly the two independent signals of §7.1, and nothing derived from
either: `agreement` (existing, `VotedLabel.agreement`) and
`support` (new, computed by ModalityGateService from the top-1 similarity
and the retrieval floor). The measured numbers are passed too, so the
rendered text can cite what was actually measured.

§7.2's closing Rule governs every string below: the disclaimer states
only what the measurement shows. The measurement shows that the top-1
similarity is below the configured floor. It does NOT show that the
archive holds no similar case -- a top-1 of 0.52 against a floor of 0.60
means a case exists and does not meet the threshold. No wording here may
be stronger than that, which is why every low-support string says "no
retrieved case meets the minimum retrieval-support threshold" and none
says the archive is empty of similar cases.
"""
from __future__ import annotations

from app.domain.entities import RetrievalSupport

# The four cells of §7.2's support matrix, as parameterised templates.
#
# Not static text (S3): each is a format string filled with the run's own
# measured agreement score, top-1 similarity, and configured floor. Not
# LLM-authored either -- the wording of a clinical evidence caveat is a
# safety property of this system, not something to re-roll on every
# generation.
#
# The high/low-support wording difference is load-bearing, not stylistic:
# S4 makes the low-support statement MANDATORY in the report, because
# DR-3 lets a report be generated from weak evidence and the doctor must
# see that in the report itself, not only on the screen.
_EN_TEMPLATES = {
    (RetrievalSupport.AT_OR_ABOVE_FLOOR, True): (
        "This report was generated by an AI assistant from retrieved similar cases and "
        "requires review and approval by a qualified radiologist. The most similar "
        "retrieved case scored {top1} against a minimum retrieval-support threshold of "
        "{floor}, and {agreement} of the retrieved cases agree on the leading finding."
    ),
    (RetrievalSupport.AT_OR_ABOVE_FLOOR, False): (
        "This report was generated by an AI assistant from retrieved similar cases and "
        "requires review and approval by a qualified radiologist. The most similar "
        "retrieved case scored {top1} against a minimum retrieval-support threshold of "
        "{floor}, but the retrieved cases conflict with each other: only {agreement} of "
        "them agree on the leading finding. Weigh the evidence for each finding "
        "individually."
    ),
    (RetrievalSupport.BELOW_FLOOR, True): (
        "This report was generated by an AI assistant from retrieved similar cases and "
        "requires review and approval by a qualified radiologist. No retrieved case "
        "meets the minimum retrieval-support threshold: the most similar case scored "
        "{top1} against a threshold of {floor}. The agreement score alone does not "
        "indicate strong evidence -- although {agreement} of the retrieved cases agree "
        "on the leading finding, they agree at a distance from this image. Treat this "
        "report as weakly supported."
    ),
    (RetrievalSupport.BELOW_FLOOR, False): (
        "This report was generated by an AI assistant from retrieved similar cases and "
        "requires review and approval by a qualified radiologist. No retrieved case "
        "meets the minimum retrieval-support threshold: the most similar case scored "
        "{top1} against a threshold of {floor}. The cases that the system retrieved also "
        "do not agree with each other -- only {agreement} of them agree on the leading "
        "finding. Treat this report as weakly supported."
    ),
}

# PROVISIONAL, UNREVIEWED placeholder terms -- a best-effort draft only,
# exactly as report_formatter.py's Bangla section headers are labelled
# under the frozen Phase 8 Decision 5. These must NOT be presented as
# clinically or linguistically validated terminology without a domain
# reviewer's sign-off, and this is a safety caveat a patient-facing report
# carries, so the review matters more here than for a section heading.
_BN_TEMPLATES = {
    (RetrievalSupport.AT_OR_ABOVE_FLOOR, True): (
        "এই রিপোর্টটি একটি এআই সহকারী দ্বারা অনুরূপ কেস থেকে তৈরি এবং একজন যোগ্য "
        "রেডিওলজিস্টের পর্যালোচনা ও অনুমোদন প্রয়োজন। সবচেয়ে অনুরূপ কেসের স্কোর {top1}, "
        "ন্যূনতম সমর্থন সীমা {floor}; প্রাপ্ত কেসগুলির {agreement} প্রধান পর্যবেক্ষণে একমত।"
    ),
    (RetrievalSupport.AT_OR_ABOVE_FLOOR, False): (
        "এই রিপোর্টটি একটি এআই সহকারী দ্বারা অনুরূপ কেস থেকে তৈরি এবং একজন যোগ্য "
        "রেডিওলজিস্টের পর্যালোচনা ও অনুমোদন প্রয়োজন। সবচেয়ে অনুরূপ কেসের স্কোর {top1}, "
        "ন্যূনতম সমর্থন সীমা {floor}; তবে প্রাপ্ত কেসগুলি পরস্পরবিরোধী — মাত্র {agreement} "
        "প্রধান পর্যবেক্ষণে একমত। প্রতিটি পর্যবেক্ষণ আলাদাভাবে বিবেচনা করুন।"
    ),
    (RetrievalSupport.BELOW_FLOOR, True): (
        "এই রিপোর্টটি একটি এআই সহকারী দ্বারা অনুরূপ কেস থেকে তৈরি এবং একজন যোগ্য "
        "রেডিওলজিস্টের পর্যালোচনা ও অনুমোদন প্রয়োজন। কোনো প্রাপ্ত কেস ন্যূনতম সমর্থন সীমা "
        "পূরণ করে না: সবচেয়ে অনুরূপ কেসের স্কোর {top1}, সীমা {floor}। শুধুমাত্র একমত্যের "
        "স্কোর শক্তিশালী প্রমাণ নির্দেশ করে না — যদিও প্রাপ্ত কেসগুলির {agreement} প্রধান "
        "পর্যবেক্ষণে একমত, তারা এই ছবি থেকে দূরে অবস্থান করে। এই রিপোর্টকে দুর্বলভাবে "
        "সমর্থিত হিসাবে বিবেচনা করুন।"
    ),
    (RetrievalSupport.BELOW_FLOOR, False): (
        "এই রিপোর্টটি একটি এআই সহকারী দ্বারা অনুরূপ কেস থেকে তৈরি এবং একজন যোগ্য "
        "রেডিওলজিস্টের পর্যালোচনা ও অনুমোদন প্রয়োজন। কোনো প্রাপ্ত কেস ন্যূনতম সমর্থন সীমা "
        "পূরণ করে না: সবচেয়ে অনুরূপ কেসের স্কোর {top1}, সীমা {floor}। সিস্টেম যে কেসগুলি "
        "পেয়েছে সেগুলিও পরস্পরের সঙ্গে একমত নয় — মাত্র {agreement} প্রধান পর্যবেক্ষণে একমত। "
        "এই রিপোর্টকে দুর্বলভাবে সমর্থিত হিসাবে বিবেচনা করুন।"
    ),
}

_TEMPLATES_BY_LANGUAGE = {
    "en": _EN_TEMPLATES,
    "bn": _BN_TEMPLATES,
}

# Shown when retrieval produced no case at all, so there is no top-1
# similarity to quote. Rendered as an em dash rather than "0.00", which
# would be a measurement that was never taken.
_NO_MEASUREMENT = "—"


def render_disclaimer(
    *,
    agreement: float | None,
    support: RetrievalSupport,
    top1_similarity: float | None,
    retrieval_floor: float,
    agreement_threshold: float,
    language: str,
) -> str:
    """S1 to S4: render the disclaimer from BOTH evidence signals.

    Keyword-only on purpose. Every parameter is a bare float and two of
    them (`agreement`, `top1_similarity`) are the two independent signals
    §7.1 forbids conflating -- positional arguments would make it possible
    to swap them at a call site and get a plausible-looking disclaimer
    computed from the wrong signal, with nothing to catch it.

    `agreement` is None when no label vote was possible (no retrieved
    cases). That is treated as low agreement: an absent vote is not
    evidence that the cases agree.
    """
    try:
        templates = _TEMPLATES_BY_LANGUAGE[language]
    except KeyError:
        # Same policy, same reasoning as ReportFormatter.format(): an
        # unexpected language code is a real bug worth surfacing, not
        # masking behind a silent English fallback that would put
        # mismatched text into a medical report.
        raise ValueError(
            f"unsupported language '{language}' -- expected one of "
            f"{sorted(_TEMPLATES_BY_LANGUAGE)}"
        ) from None

    # §7.1's Rule: the disclaimer must read BOTH signals. The matrix key
    # is (support, is_high_agreement) -- neither component is derived from
    # the other, which is §7's whole point.
    is_high_agreement = agreement is not None and agreement >= agreement_threshold
    template = templates[(support, is_high_agreement)]

    return template.format(
        top1=f"{top1_similarity:.2f}" if top1_similarity is not None else _NO_MEASUREMENT,
        floor=f"{retrieval_floor:.2f}",
        agreement=f"{agreement:.0%}" if agreement is not None else _NO_MEASUREMENT,
    )
