"""create patients table and add retrieval_sessions.patient_id

Revision ID: 96e0dd80c317
Revises: 719b6078d895
Create Date: 2026-07-13 19:59:20.987812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96e0dd80c317'
down_revision: Union[str, Sequence[str], None] = '719b6078d895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('patients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_code')
    )
    # add_column/create_index are plain ALTER TABLE ADD COLUMN / CREATE
    # INDEX -- SQLite supports both natively, confirmed empirically (a real
    # `alembic upgrade` run got past both of these before failing at the
    # next step). NOT wrapped in batch mode, since neither needs it.
    op.add_column('retrieval_sessions', sa.Column('patient_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_retrieval_sessions_patient_id'), 'retrieval_sessions', ['patient_id'], unique=False)
    # SQLite has no ALTER TABLE ADD CONSTRAINT -- adding a foreign key to an
    # already-existing table requires Alembic's batch mode (SQLite-specific
    # recreate/copy/rename strategy). Confirmed empirically, not assumed:
    # the autogenerated bare `op.create_foreign_key(...)` here raised
    # `NotImplementedError: No support for ALTER of constraints in SQLite
    # dialect` on a real run. Given an explicit name (rather than
    # autogenerate's `None`) so downgrade can reference it directly.
    with op.batch_alter_table('retrieval_sessions', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_retrieval_sessions_patient_id_patients', 'patients', ['patient_id'], ['id']
        )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('retrieval_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_retrieval_sessions_patient_id_patients', type_='foreignkey')
    op.drop_index(op.f('ix_retrieval_sessions_patient_id'), table_name='retrieval_sessions')
    op.drop_column('retrieval_sessions', 'patient_id')
    op.drop_table('patients')
