"""create retrieval_sessions and retrieved_evidence

Revision ID: e60f9520da7b
Revises: 
Create Date: 2026-07-12 00:35:20.495305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e60f9520da7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retrieval_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('query_image_path', sa.String(), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('min_similarity', sa.Float(), nullable=False),
    sa.Column('num_results', sa.Integer(), nullable=False),
    sa.Column('retrieval_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retrieved_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('study_uid', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['retrieval_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieved_evidence_session_id'), 'retrieved_evidence', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retrieved_evidence_session_id'), table_name='retrieved_evidence')
    op.drop_table('retrieved_evidence')
    op.drop_table('retrieval_sessions')
    # ### end Alembic commands ###
