"""create comparisons table

Revision ID: fc0fc7f35ef5
Revises: 96e0dd80c317
Create Date: 2026-07-13 20:45:04.444555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0fc7f35ef5'
down_revision: Union[str, Sequence[str], None] = '96e0dd80c317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparisons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('previous_report_id', sa.Uuid(), nullable=False),
    sa.Column('current_report_id', sa.Uuid(), nullable=False),
    sa.Column('deterministic_facts', sa.JSON(), nullable=False),
    sa.Column('llm_narrative', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['previous_report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparisons_current_report_id'), 'comparisons', ['current_report_id'], unique=False)
    op.create_index(op.f('ix_comparisons_patient_id'), 'comparisons', ['patient_id'], unique=False)
    op.create_index(op.f('ix_comparisons_previous_report_id'), 'comparisons', ['previous_report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comparisons_previous_report_id'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_patient_id'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_current_report_id'), table_name='comparisons')
    op.drop_table('comparisons')
    # ### end Alembic commands ###
